[build]
command = "cd apps/we-dev-next && pnpm install && pnpm build"
pages_build_output_dir = "apps/we-dev-next/.next"

[env.production]
name = "we-dev"

[env.production.vars]
NEXT_PUBLIC_APP_NAME = "we-dev"